CREATE TABLE SENSOR (
    SENSOR_ID INT NOT NULL AUTO_INCREMENT,
    SENSOR_NAME CHAR(50) NOT NULL,
    UPDATE_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (SENSOR_ID)
);

CREATE TABLE PLANT (
    ID INT NOT NULL AUTO_INCREMENT,
    IP CHAR(15) NOT NULL, 
    STATUS CHAR(8),
    UPDATE_TIME TIMESTAMP NOT NULL,    
    PRIMARY KEY (ID)
); 

CREATE TABLE SENSOR_TRANSECTION (
    PLANT_ID INT NOT NULL,
 SENSOR_ID INT NOT NULL,
 SENSOR_VALUES DOUBLE NOT NULL ,
 LAST_UPDATE TIMESTAMP
 
);

INSERT INTO PLANT VALUES(1,'192.168.0.1','Y',now());
INSERT INTO PLANT VALUES(2,'192.168.0.1','Y',now());